In [2]:
import numpy as np

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [6]:
two_array = np.empty((2, 2))

2. Initialize an all one array with size 4X2.

In [7]:
four_array = np.empty((4, 2))

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [9]:
rows = 3
columns = 4
array = np.full((rows,columns), fill_value = 6)
print(array)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [11]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [8, 9, 10]])
new_array = np.zeros_like(array1)
print(new_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [14]:
array = np.array([[1, 2, 3], [4, 5, 6], [8, 9, 10]] )
new_array = np.ones_like(array)
print(new_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [15]:
new_list = [1, 2, 3, 4]
new_list= np.array(new_list)
print(type(new_list))

<class 'numpy.ndarray'>


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [3]:
num_array = np.arange(10,50)
num_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [4]:
matrix_array = np.arange(0,9)
matrix_array = np.reshape(matrix_array, (3,3))
matrix_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [5]:
mat_array = np.eye(3)
mat_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [18]:
array = np.random.random(30) * 3
array_mean = array.mean()
float(array_mean)


1.5469632565872944

5. Create a 10X10 array with random values and find the minimum and maximum values.


In [24]:
array = np.random.randint(1, 50, size = (10, 10))
min = np.min(array)
max = np.max(array)
print(f"Array : {array}\n Minimum values : {min} \n Maximum values : {max}")

Array : [[ 6 16 19 29 39 26 19 16 36 21]
 [20 37  7  2 12 42 48 17 12 17]
 [38  9 29 15 21 14  3 13 37 16]
 [ 8 46 31 38 44  7  6 23 38 20]
 [32 33 22 30 33 14 15 35 33  5]
 [49 16 38  8  9 27 15 35 16 30]
 [15 26 10 15 31 24 32 48 26 20]
 [ 8 44 36 27  6 26 10 45 34 47]
 [34  2  4 22 10 29 39 36 10  4]
 [20 10  8 44  5 15  8 22  9 38]]
 Minimum values : 2 
 Maximum values : 49


6. Create a zero array of size 10 and replace 5th element with 1.


In [27]:
array = np.zeros(10)
print(" Array before: ", array)
array[4] = 1
print("Array After : ", array)

 Array before:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array After :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [29]:
arr = np.array([1, 2, 0, 0, 4, 0])
reverse_array = np.flip(arr)
print(f"Array before : {arr}")
print(f"Array after reversed : {reverse_array}")

Array before : [1 2 0 0 4 0]
Array after reversed : [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [30]:
array = np.zeros((2, 2))
array[0][0] = 1
array[1][1] = 1
print(array)

[[1. 0.]
 [0. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [32]:
array = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i % 2 == 0 and j % 2 != 0):
      array[i][j] = 1
    elif(i % 2 != 0 and j % 2 == 0):
      array[i][j] = 1
array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.


In [34]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
np.add(x, y)

array([[ 6,  8],
       [10, 13]])

2. Subtract the two array.


In [36]:
np.subtract(x, w)

array([[-10, -10],
       [ -8,  -7]])

3. Multiply the array with any integers of your choice.


In [37]:
np.multiply(y, 6)

array([[30, 36],
       [42, 48]])

4. Find the square of each element of the array.


In [40]:
np.power(w, 2)

array([121, 144])

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [41]:
print("Dot product between v and w : " , np.dot(v, w))
print("Dot product between x and v : " , np.dot(x, v))
print("Dot product between x and y : " , np.dot(x, y))

Dot product between v and w :  219
Dot product between x and v :  [29 77]
Dot product between x and y :  [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.


In [44]:
np.concatenate((x, y))
np.concatenate((v, w))

array([ 9, 10, 11, 12])

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

Ans- Since x array has 2 dimension it showed error beacuse all input array must have same number of dimension

In [45]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.




In [46]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

prob= np.linalg.inv(A)
np.dot(A, prob)


array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

2. Prove AB ̸= BA.


In [47]:
print("A.B : ", np.dot(A, B))
print("B.A : ", np.dot(B, A))

A.B :  [[23 13]
 [51 29]]
B.A :  [[36 44]
 [13 16]]


3. Prove (AB)T = B^T.A^T


In [50]:
AB = np.dot(A,B)
AB_transpose = np.transpose(AB)

A_transpose = np.transpose(A)
B_transpose = np.transpose(B)

BTAT = np.dot(B_transpose, A_transpose)

print("(A.B)^T : ", AB_transpose)
print("B^T.A^T : ", BTAT)


(A.B)^T :  [[23 51]
 [13 29]]
B^T.A^T :  [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}



In [54]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

inv_of_A = np.linalg.inv(A)
C = np.dot(inv_of_A, B)
print(C)


[ 2.  1. -2.]
